### ISSUE TITLE
MessagingServiceを使っていないが、AndroidでMessagingServiceのエラーが発生する

### ISSUE THREAD

**Issue by wataru-hasegawa** [NIFCLOUD-mbaas/UserCommunity#1278]
Unity製のアプリを先日リリースしました。
タイトルにも記載しましたが、同アプリではMessagingServiceは使用していないのですがなぜかMessagingServiceのエラーが発生してしまっています。

同機能を利用しない場合も何かしらの設定作業が必要なのでしょうか？
ユーザーコミュニティーで質問する内容ではない気もしますが、ご存じの方いらっしゃったらご教授ください。

以下Crashlyticsでキャッチしたエラーになります。

タイトル
>NCMBFirebaseMessagingService.java line 58
com.nifcloud.mbaas.ncmbfcmplugin.NCMBFirebaseMessagingService.onNewToken

スタックトレース(長いので一部のみ記載)

>Fatal Exception: java.lang.Error: FATAL EXCEPTION [Firebase-NCMBFirebaseMessagingService]
Unity version     : 2020.3.9f1
Device model      : Google Pixel 3
Device fingerprint: google/blueline/blueline:9/xxxxxxxxxxx:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

>Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
       at com.nifcloud.mbaas.ncmbfcmplugin.NCMBFirebaseMessagingService.onNewToken(NCMBFirebaseMessagingService.java:58)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:94)
       at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.6.0:2)
       at java.lang.Thread.run(Thread.java:764)

>Instr: androidx.test.runner.AndroidJUnitRunner
       at java.lang.Thread.sleep(Thread.java)
       at java.lang.Thread.sleep(Thread.java:373)
       at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:391)
       at androidx.test.tools.crawler.obfuscated.bj.ah.sleepUninterruptibly(Uninterruptibles.java:3)
       at androidx.test.tools.crawler.platform.RemotePlatform.startCrawlAndWaitUntilFinished(RemotePlatform.java:13)
       at androidx.test.tools.crawler.CrawlPlatform.testEntry(CrawlPlatform.java:2)
       at java.lang.reflect.Method.invoke(Method.java)
       at androidx.test.tools.crawler.obfuscated.fk.d.runReflectiveCall(FrameworkMethod.java:1)
       at androidx.test.tools.crawler.obfuscated.fc.c.run(ReflectiveCallable.java:1)
       at androidx.test.tools.crawler.obfuscated.fk.e.invokeExplosively(FrameworkMethod.java:1)
       at androidx.test.tools.crawler.obfuscated.fe.g.evaluate(InvokeMethod.java:1)
       at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:8)
       at androidx.test.tools.crawler.obfuscated.fj.i.evaluate(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.a.evaluate(BlockJUnit4ClassRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.m.runLeaf(ParentRunner.java:2)
       at androidx.test.tools.crawler.obfuscated.fj.d.runChild(BlockJUnit4ClassRunner.java:5)
       at androidx.test.tools.crawler.obfuscated.fj.d.runChild(BlockJUnit4ClassRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.j.run(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.g.schedule(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.m.runChildren(ParentRunner.java:2)
       at androidx.test.tools.crawler.obfuscated.fj.m.access$100(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.h.evaluate(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.i.evaluate(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.m.run(ParentRunner.java:4)
       at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.r.runChild(Suite.java:2)
       at androidx.test.tools.crawler.obfuscated.fj.r.runChild(Suite.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.j.run(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.g.schedule(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.m.runChildren(ParentRunner.java:2)
       at androidx.test.tools.crawler.obfuscated.fj.m.access$100(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.h.evaluate(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.i.evaluate(ParentRunner.java:1)
       at androidx.test.tools.crawler.obfuscated.fj.m.run(ParentRunner.java:4)
       at androidx.test.tools.crawler.obfuscated.fg.c.run(JUnitCore.java:5)
       at androidx.test.tools.crawler.obfuscated.fg.c.run(JUnitCore.java:1)
       at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:6)
       at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:16)
       at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by goofmint** [comment]
こちら参考になるでしょうか？

https://blog.mbaas.nifcloud.com/entry/2020/06/26/101436

**Comment by wataru-hasegawa** [comment]
@goofmint 
記事のご共有ありがとうございます！
記事はiosについてですが、Androidでも取り除けそうな気がします。
確認後に試してみます。ありがとうございます！
