### ISSUE TITLE
ncmb-cliで会員データのimportが出来ない

### ISSUE THREAD

**Issue by nobunobu123** [NIFCLOUD-mbaas/UserCommunity#1290]
ncmbの会員データへcsvデータをimportしたく、ncmb-cliをインストールしました。
（参考URL：https://blog.mbaas.nifcloud.com/entry/2019/11/25/192634）

アプリケーションキーとクライアントキーを設定し、importを実行するとエラーが出てimportができません。
（補足：exportはできたので、アプリケーションキーとクライアントキーはうまく設定できているはずです。）

どのようにすれば、会員データをimportできますでしょうか。

ご教授、何卒宜しくお願いいたします。

【コード】
ncmb csv import --classname User test.csv -b -d --object -l

【エラー内容】
C:\Users\ユーザー名\AppData\Roaming\npm\node_modules\ncmb-cli\lib\common.js:106
      let parser = parse({delimiter: ',', columns: true}, function(err, data) {

TypeError: parse is not a function
    at C:\Users\ユーザー名\AppData\Roaming\npm\node_modules\ncmb-cli\lib\common.js:106:20
    at new Promise (<anonymous>)
    at Object.csv2json (C:\Users\ユーザー名\AppData\Roaming\npm\node_modules\ncmb-cli\lib\common.js:104:12)
    at main (C:\Users\ユーザー名\AppData\Roaming\npm\node_modules\ncmb-cli\bin\ncmb-csv-import:41:18)
    at C:\Users\ユーザー名\AppData\Roaming\npm\node_modules\ncmb-cli\bin\ncmb-csv-import:30:5

【CSVデータ（test.csv）】
userName,mailAddress,password
"test","","test"

**Comment by nobunobu123** [comment]
補足なのですが、エクスポート出来たのは会員データではなく、データストア内のものになります。
