### ISSUE TITLE
Androidのサインアップ時に発生するMainThreadExceptionについて。

### ISSUE THREAD

**Issue by flatfisher** [NIFCloud-mbaas/UserCommunity#188]
Androidのサインアップ時に、時々MainThreadExceptionが発生します。
どなたか同じ現象が発生する方いらっしゃいますか？

スレッド関連はSDKで管理されているはずなのですが、何かのタイミングで発生するのかもしれません。

原因を追求してみます。

**Comment by moongift** [comment]
@flatfisher 
もしログがあれば提示してもらえると何か言えるかも知れません。時々、というのが難しいところです。

**Comment by flatfisher** [comment]
moongift さん、コメントありがとうございます。
失礼しました。エラーのタイミングですが、初めてログインした際に発生するようです。
またログインだけではなく、ログアウトでもNetworkOnMainThreadExceptionが発生しました。
一先問題の場所をAsyncTaskで囲ってみます。

またスレ違いですが、ラベルの付け方を教えて頂きたいです。
Androidのlabelをつけて頂きありがとうございます。

ログは以下の様なエラーログがでています。
07-21 09:52:50.584    3297-3297/ E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: , PID: 3297
    android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
            at java.net.InetAddress.getAllByName(InetAddress.java:214)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
            at com.nifty.cloud.mb.CommonConnection.connect(CommonConnection.java:233)
            at com.nifty.cloud.mb.CommonConnection.connect(CommonConnection.java:174)
            at com.nifty.cloud.mb.NCMBUser.logOut(NCMBUser.java:316)
            at MainFragment.logOut(MainFragment.java:50)
            at MainFragment.onClick(MainFragment.java:43)
            at android.view.View.performClick(View.java:4438)
            at android.view.View$PerformClick.run(View.java:18422)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
