### ISSUE TITLE
【Cocos2d-x】【Android】プッシュ通知受信時にClassNotFoundException

### ISSUE THREAD

**Issue by Corvus400** [NIFCLOUD-mbaas/UserCommunity#395]
- AndroidStudioでプレーンなプロジェクトを作り、[ドキュメント](http://mb.cloud.nifty.com/doc/current/push/basic_usage_android.html)に従って実装した際にはプッシュ通知は問題なく表示され、通知を押すとActivityが起動するのですが、導入したい既存のCocos2d-xのプロジェクトでは表題のようにプッシュ通知を受信するとクラッシュしてしまいます。
- Cocos2dxの方では、AndroidStudioでファイルを開くことができない(proj.android-studioフォルダが作成されないため)ためXcodeでファイル単体を開いて記述をしています。
- パスの指定が間違っていると考えているのですが、調べてみたものの情報が見つからず、解決できず困っています。助けて頂けますか？
- logcatの出力は以下になります。

```

03-11 15:48:30.444 5996-6033/(パッケージ名) E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                     Process: (アプリ名), PID: 5996
                                                                     java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: (パッケージ名)/org.cocos2dx.cpp.MyApplication
                                                                         at com.nifty.cloud.mb.core.NCMBGcmListenerService.notificationSettings(NCMBGcmListenerService.java:113)
                                                                         at com.nifty.cloud.mb.core.NCMBGcmListenerService.sendNotification(NCMBGcmListenerService.java:44)
                                                                         at com.nifty.cloud.mb.core.NCMBGcmListenerService.onMessageReceived(NCMBGcmListenerService.java:34)
                                                                         at com.google.android.gms.gcm.GcmListenerService.zzq(Unknown Source)
                                                                         at com.google.android.gms.gcm.GcmListenerService.zzp(Unknown Source)
                                                                         at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
                                                                         at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
                                                                         at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:841)
                                                                      Caused by: java.lang.ClassNotFoundException: (パッケージ名)/org.cocos2dx.cpp.MyApplication
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.Class.forName(Class.java:251)
                                                                         at java.lang.Class.forName(Class.java:216)
                                                                         at com.nifty.cloud.mb.core.NCMBGcmListenerService.notificationSettings(NCMBGcmListenerService.java:111)
                                                                         at com.nifty.cloud.mb.core.NCMBGcmListenerService.sendNotification(NCMBGcmListenerService.java:44) 
                                                                         at com.nifty.cloud.mb.core.NCMBGcmListenerService.onMessageReceived(NCMBGcmListenerService.java:34) 
                                                                         at com.google.android.gms.gcm.GcmListenerService.zzq(Unknown Source) 
                                                                         at com.google.android.gms.gcm.GcmListenerService.zzp(Unknown Source) 
                                                                         at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source) 
                                                                         at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source) 
                                                                         at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:841) 

```
- AndroidManifestのmeta data(openPushStartActivity)は以下のように記述しています。

```

<meta-data
            android:name="openPushStartActivity"
            android:value="/org.cocos2dx.cpp.MyApplication" />

```
- フレームワークとNCMBのバージョンは以下になります。
- cocos2d-x framework 3.8
- NCMB v2.2.0

---
- jarフォルダには(他にも入っていますが)jarファイルを持ってきて入れています。
- /Library/Android/sdk/extras/android/support/v7/appcompat/libs/android-support-v4.jar より
- /Library/Android/sdk/extras/android/support/v7/appcompat/libs/android-support-v7-appcompat.jar より
- https://github.com/NIFTYCloud-mbaas/ncmb_android/releases/download/v2.2.0/NCMB.2.2.0.zip より

**Comment by Corvus400** [comment]
- 自己解決しましたので、Qiitaに記事として手順をまとめました。[こちらをご覧下さい](http://qiita.com/Corvus400/items/10b59466f92a12c1207c)
