### ISSUE TITLE
javascriptで会員をロールに追加すると E403005:fieldName must not be entered が発生

### ISSUE THREAD

**Issue by spring582k** [NIFCloud-mbaas/UserCommunity#885]
ご存知の方、情報頂けないでしょうか。
下記サンプルコード：会員をロールに追加する を実行すると、
http://mb.cloud.nifty.com/doc/current/sdkguide/javascript/role.html#%E4%BC%9A%E5%93%A1%E3%82%92%E3%83%AD%E3%83%BC%E3%83%AB%E3%81%AB%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B

以下のように、POSTエラー 403が返されます。
会員認証設定は、IDとメールアドレス認証の両方を「許可する」にしてあります。
会員レコードの、mailAddressConfirm 列はtrueになっています。
<pre>
{ Error: cannot POST /2013-09-01/roles (403)
    at Response.toError (/home/foo/node_modules/superagent/lib/node/response.js:106:13)
    at Response.setStatusProperties (/home/foo/node_modules/superagent/lib/node/response.js:183:12)
    at new Response (/home/foo/node_modules/superagent/lib/node/response.js:42:8)
    at IncomingMessage.<anonymous> (/home/foo/node_modules/superagent/lib/node/index.js:918:22)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 403,
  text:
   '{"code":"E403005","error":"fieldName must not be entered."}',
  method: 'POST',
  path: '/2013-09-01/roles',
  code: 'E403005',
  error: 'fieldName must not be entered.' }
</pre>

以上、よろしくお願いします。

**Comment by goofmint** [comment]
expertPlan というロールは存在しますか？後はコードを見てみないと何とも…。

**Comment by spring582k** [comment]
@goofmint ありがとうございます。ロールは実在するものに書き換えていました。
以下、全コードを記載させていただきます、アドバイスいただけると助かります。

<pre>
ar NCMB = require("ncmb");
var ncmb = new NCMB("xxx","yyy");

var email = "foo@bar.com";
var pwd = "zzz";

ncmb.User.loginWithMailAddress(email, pwd)
.then(function(user){
        console.log(user.userName);

        ncmb.Role.equalTo("roleName", "shop").fetch()
        .then(function (role){
                if (JSON.stringify(role) === "{}") {
                        console.log("role does not exist.");
                } else {
                        role.addUser(user).save()
                        .then(function (data) {
                                console.log("ok");
                        })
                        .catch(function (err) {
                                console.log(err);
                        });
                }
        })
        .catch(function (err){
                console.log(err);
        });

})
.catch(function(err){
        console.log(err);
});
</pre>

**Comment by goofmint** [comment]
`role.addUser(user).save()` ではなく `role.addUser(user).update()` ですね。既存のroleに対する更新処理なので。ドキュメントも間違っているようです。

**Comment by spring582k** [comment]
@goofmint 通りました！助かりました。
