### ISSUE TITLE
swift4.2でプッシュ通知がうまくできません

### ISSUE THREAD

**Issue by Tsolaratov** [NIFCloud-mbaas/UserCommunity#999]

**Comment by goofmint** [comment]
どこで詰まっているのでしょうか？

1. 証明書の作成
2. デバイスを開発者用に設定
3. PodfileからSDKインストール部分
4. ブリッジヘッダーファイル部分
5. NCMB初期化
6. デバイストークン取得&保存

などに分割できるとは思いますが。詰まっている部分が分からないと（逆に何ができているのか分からないと）教えるのは難しいかなと。

**Comment by Tsolaratov** [comment]
お返事ありがとうございます。
１　出来ています
２　開発者用に設定の意味が正確にわかりませんがデベロッパー登録しているものなっています
３　Podfileの設定なんですがhttps://blog.mbaas.nifcloud.com/entry/2018/10/17/163302を参考にしました。
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '(プロジェクト名)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for (プロジェクト名)
  pod 'NCMB', :git => 'https://github.com/NIFCloud-mbaas/ncmb_ios.git'
  
  target '(プロジェクト名)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '(プロジェクト名)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

plugin 'cocoapods-keys', {
  :project => "(プロジェクト名)",
  :keys => [
    "applicationKey",
    "clientKey"
  ]}
これを
pod installすると
 Unable to find a target named `ncmbpushTests`, did find `ncmbpush`.
と出てしまいます。
ちなみに
 target '(プロジェクト名)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '(プロジェクト名)UITests' do
    inherit! :search_paths
    # Pods for testing
  end
の部分を削除してrunしてみますと
'NCMB/NCMB.h' file not found
Failed to emit~
の２つのエラーが出ます。
他は
https://blog.mbaas.nifcloud.com/entry/2018/10/24/135658
を参考にして進めてみました。

つまりところcocoapod-keyやrubyを使ってgemfile云々はなんとかできているとは思うのですが、Podfileの部分で最初のつまずきが出ていると思うのです。

**Comment by Tsolaratov** [comment]
pod install --verbose
  Preparing
    - Running pre install hooks
      - cocoapods-keys from
      `/Library/Ruby/Gems/2.3.0/gems/cocoapods-keys-2.1.0/lib/plugin.rb`

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-ncmbpush`: (``)
[!] Unable to find a target named `ncmbpushTests`, did find `ncmbpush`.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer/target_inspector.rb:108:in `compute_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer/target_inspector.rb:40:in `compute_results'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:1028:in `block (3 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:1026:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:1026:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:1024:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:1024:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:1019:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:96:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:266:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:136:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

[!] Automatically assigning platform `ios` with version `12.1` on target `ncmbpush` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by goofmint** [comment]
> Unable to find a target named `ncmbpushTests`, did find `ncmbpush`.

のエラーはXcodeでプロジェクトを作成する際にUnit Testを除外しているせいです。なので〜Tests、UITestsのブロックは不要です。

> の部分を削除してrunしてみますと

runというのはどういうコマンドを実行したのでしょうか？

**Comment by Tsolaratov** [comment]
お返事ありがとうございます。
runなんて書いてすみません。
実機で動作させようとすると、という意味です。

アドバイスによると、pod file上にTest UITest

**Comment by goofmint** [comment]
そうですね。テストがないので

```
target '(プロジェクト名)Tests' do
  inherit! :search_paths
  # Pods for testing
end

target '(プロジェクト名)UITests' do
  inherit! :search_paths
  # Pods for testing
end`
```

は不要です。これがない状態で `pod install` をターミナルで実行するといかがでしょう？

**Comment by Tsolaratov** [comment]
ありがとうございます。
実はそれがない状態でpod installを既に試してみました。
すうするとエラーが２つ出てきてしまいます。
‘NCMB/NCMB.h’ file not found 
と
Failed to emit ~
の２つです

**Comment by goofmint** [comment]
NCMB/NCMB.hに関するエラーはこのステップの時点では本来書いていないはずです。何か次のステップに進めていませんか？一度Xcodeのプロジェクトを作り直した方が良いかも知れません。

**Comment by Tsolaratov** [comment]
分かりました。
１つ１つやり直してみます。

**Comment by Tsolaratov** [comment]
返信を下さった方へ報告させていただきます。
結論から申し上げますと、プッシュ通知がうまく動作しました。
ありがとうございます。
